version: "3"

services:
  db:
    image: "mysql"
    container_name: sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: kosh
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_pw
    ports:
      - 3306:3306
    volumes:
      - "~/data/kosh/db:/var/lib/mysql"
    networks:
      - tattle

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - "~/data/kosh/mongo:/data/db"
    networks:
      - tattle

  db_gui:
    image: adminer
    container_name: sql_ui
    restart: always
    ports:
      - 8080:8080
    networks:
      - tattle

  backend:
    build:
      context: ./src/backend
      target: debug
    container_name: kosh_api
    restart: always
    command: nodemon index.js
    ports:
      - 10001:8000
      - 9229:9229
    volumes:
      - "./src/backend:/app"
    env_file:
      - ./src/backend/development.env
    networks:
      - tattle

networks:
  tattle:
    driver: bridge
